config/routes.rb
Rails.application.routes.draw do
  root 'minesweeper_boards#index'
  post 'generate_board', to: 'minesweeper_boards#generate'
  get 'boards/:id', to: 'minesweeper_boards#show', as: :board
  get 'boards', to: 'minesweeper_boards#new', as: :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minesweeper_board.rb
class MinesweeperBoard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minesweeper_boards_controller.rb
class MinesweeperBoardsController < ApplicationController
    def generate_board(width, height, mines)
        board = Array.new(height) { Array.new(width) { { revealed: false, mine: false, neighbor_mines: 0 } } }
        
        placed_mines = 0
        while placed_mines < mines
            x = rand(width)
            y = rand(height)

            next if board[y][x][:mine]

            board[y][x][:mine] = true
            placed_mines += 1
        end

        # Update neighbor_mines count for all cells based on mine placement
        (0...height).each do |y|
            (0...width).each do |x|
            next if board[y][x][:mine]

            (-1..1).each do |dy|
                (-1..1).each do |dx|
                ny = y + dy
                nx = x + dx
                next unless ny.between?(0, height - 1) && nx.between?(0, width - 1)

                board[y][x][:neighbor_mines] += 1 if board[ny][nx][:mine]
                end
            end
            end
        end

        board
    end    
    
    def new
        @minesweeper_board = MinesweeperBoard.new
        @recent_boards = MinesweeperBoard.order(created_at: :desc)
      end
    
      def generate
        @minesweeper_board = MinesweeperBoard.new(minesweeper_board_params)
    
        if @minesweeper_board.save
          width = @minesweeper_board.width
          height = @minesweeper_board.height
          mines = @minesweeper_board.mines
    
          board_data = generate_board(width, height, mines)
          @minesweeper_board.data = board_data.to_json
          @minesweeper_board.save
    
          redirect_to board_path(@minesweeper_board)
        else
          render :new
        end
      end
    
      def show
        @minesweeper_board = MinesweeperBoard.find(params[:id])
      end
    
      def index
        @recent_boards = MinesweeperBoard.order(created_at: :desc).limit(10)
      end
    
      private
    
      def minesweeper_board_params
        params.require(:minesweeper_board).permit(:email, :board_name, :width, :height, :mines)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minesweeper_boards_helper.rb
module MinesweeperBoardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinesweeperApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "Minesweeper App", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Generate Board", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List of Boards", boards_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/minesweeper_boards/index.html.erb
<h2>Welcome!</h2>
<p>Generate your Minesweeper board:</p>

<%= form_with(model: @minesweeper_board, url: generate_board_path, method: :post) do |form| %>
  <div class="row mb-3">
    <div class="col">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="col">
      <%= form.label :board_name %>
      <%= form.text_field :board_name, class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <%= form.label :board_width %>
      <%= form.number_field :width, class: "form-control" %>
    </div>
    <div class="col">
      <%= form.label :board_height %>
      <%= form.number_field :height, class: "form-control" %>
    </div>
    <div class="col">
      <%= form.label :mines %>
      <%= form.number_field :mines, class: "form-control" %>
    </div>
  </div>
  <%= form.submit "Generate Board", class: "btn btn-primary" %>
<% end %>
</br>
<% if @recent_boards.present? %>
  <h3>Top <%= @recent_boards.count %> Recent Boards</h3>
  <ul class="list-group">
    <% @recent_boards.first(10).each do |board| %>
      <li class="list-group-item">
        <%= link_to board.board_name, board_path(board) %>
        - <%= board.email %> (Created at: <%= board.created_at.strftime('%B %d, %Y') %>)
      </li>
    <% end %>
  </ul>
  <%= link_to "View All Generated Boards", boards_path, class: "btn btn-primary mt-3" %>
<% else %>
  <p>No recent boards yet.</p>
<% end %>

app/views/minesweeper_boards/new.html.erb
<div class="container">
  Total(<%= @recent_boards.count %>)
  <h2>Lists of Minesweeper Boards </h2>
  <ul class="list-group">
    <% @recent_boards.each do |board| %>
      <li class="list-group-item">
        <%= link_to board.board_name, board_path(board) %>
        - <%= board.email %> (Created at: <%= board.created_at.strftime('%B %d, %Y') %>)
      </li>
    <% end %>
  </ul>
</div>

app/views/minesweeper_boards/show.html.erb
<div class="container">
  <h2><%= @minesweeper_board.board_name %></h2>
  <p>Generated by: <%= @minesweeper_board.email %></p>

  <table class="table table-bordered table-hover">
    <% board_data = JSON.parse(@minesweeper_board.data) %>
    <% board_data.each_with_index do |row, row_idx| %>
      <tr>
        <% row.each_with_index do |cell, col_idx| %>
          <td>
              <% if cell['mine'] %>
              <%= image_tag('bomb.png', class: 'cell-image') %>
              <% else %>
              <%= image_tag('whitetile.png', class: 'cell-image') %>
              <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>